ALTER TABLE users ADD COLUMN telegram_chat_id INTEGER UNIQUE;

CREATE TABLE IF NOT EXISTS user_repositories (
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    repo_id INTEGER NOT NULL REFERENCES repositories(id) ON DELETE CASCADE,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, repo_id)
);
